import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ✅ Apply Nunito variable to body */}
      <body className={nunito.variable}>{children}</body>
    </html>
  );
}
